In [23]:
import numpy as np

# Define as dimensões da matriz
linhas = 6
colunas = 3

# Cria uma matriz com distribuição aleatória de 0s e 1s
matriz1 = np.random.randint(2, size=(linhas, colunas))

matriz1[2,1] = 2

# Imprime a matriz
print(matriz1)

[[0 1 1]
 [1 1 1]
 [1 2 1]
 [1 1 1]
 [0 0 1]
 [1 0 0]]


In [22]:
if matriz1[1,1] == 0:
    matriz2 = np.roll(matriz1, 1, axis=0)
    matriz2[2,1]=2
    matriz2[3,1]=0
else:
    if matriz1[2,0]==0:
        if matriz1[1,0]==0:
            matriz2=np.roll(matriz1, 1, axis=0)
            matriz2[1,0] = 2
            matriz2[2,1]=0
print(matriz2)

[[1 0 0]
 [1 0 0]
 [0 2 0]
 [1 0 1]
 [0 0 0]
 [0 0 0]]


In [19]:
matriz2 = np.roll(matriz1, 1, axis=0)
matriz2[2,1] = 2
matriz2[3,1] = 0
# Imprime a matriz deslocada
print("Matriz deslocada:")
print(matriz2)

Matriz deslocada:
[[1 0 0]
 [1 0 0]
 [0 2 0]
 [1 0 1]
 [0 0 0]
 [0 0 0]]


In [ ]:
if matriz2[1,1] = 1:
    if 